### ISSUE TITLE
Provide architecture specific .apk files rather than the universal one

### ISSUE THREAD

**Issue by 2011** [oxen-io/session-fdroid#5]
Some F-Droid repositories (Bromite, for example), and even some apps in the F-Droid repository (VLC, for example) provide separate .apk files (x86_64, arm64-v8a, x86, and armeabi-v7a) for each architecture. In those cases, F-Droid does always suggest the correct variant. I have noticed in the releases that Session builds all four of the .apk files, but the Session F-Droid repository only offers the "universal" .apk.

Can someone explain why? :)

I mention this because at least one F-Droid repo has started to mirror your releases, but only the armeabi-v7a variant. Unfortunately, F-Droid wants to suggest that upgrade (on my arm64-v8a devices) instead of the upgrade with the higher build version, same architecture, and same repository source. I want to find a way to get F-Droid to suggest the best variant, and hope that I can convince F-Droid to make the necessary tweaks in their client. Perhaps offering specific builds for each architecture will help.

**Comment by hjubb** [comment]
Currently the architecture specific builds have different version codes based on the architecture. I think this is inherited from Signal (possibly from their release processes, which we don't really use any more). This means that uploading all or multiple architecture versions for Session will currently prompt you to always update to the universal. We can probably change the release code to always use the exact same build codes but would have to give it a bit of a test! That should solve it moving forward

**Comment by 2011** [comment]
> Currently the architecture specific builds have different version codes based on the architecture. I think this is inherited from Signal (possibly from their release processes, which we don't really use any more).

Yes, every application does that (even Google Play Services has several variants for each release with the same version but different build numbers depending on the capabilities of specific Android versions).

> This means that uploading all or multiple architecture versions for Session will currently prompt you to always update to the universal. We can probably change the release code to always use the exact same build codes but would have to give it a bit of a test! That should solve it moving forward

I don't think you want to do that. The latest version of Bromite for example, has four variants of the latest release (104.0.5112.91) - 1659916910, 1659916920, 1659916960, and 1659916970. On the Bromite page in the F-Droid app, the version list (on an Android device) shows the x86 variants as "Incompatible," with red "Requires x86_64" or "Requires x86" at the bottom of the entry (and on a armeabi-v7a device, the arm64-v8a variant shows as incompatible, as well). F-Droid will suggest an appropriate variant (but you should keep a higher build number for x86_64 than x86 and for arm64-v8a compared to armeabi-v7a to make certain that the optimal variant gets installed).

You can also check out VLC in the F-Droid repository to see how this works.

**Comment by hjubb** [comment]
Closing as we are currently following this approach now
