### ISSUE TITLE
"no attributes for entry.json"

### ISSUE THREAD

**Issue by 2011** [oxen-io/session-fdroid#9]
Whenever I attempt to update the F-Droid repositories I have enabled, I get the following message:

"Session F-Droid no attributes for entry.json
All other repos didn't create errors"

Does this represent a problem?

**Comment by mrunix00** [comment]
Still not fixed

**Comment by ThomasSession** [comment]
We had an issue with the latest release but it should hopefully be resolved now.
Thanks~

**Comment by ThomasSession** [comment]
Are you happy for us to close the issue?

**Comment by ThomasSession** [comment]
F-Droid build is back to normal.
